[project]
name = "-vehicle-scraper"
version = "0.1.0"
description = "A fast vehicle data scraper for retrieving information using registration numbers"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "flask>=3.1.0",
    "requests>=2.32.3",
]
